publish:
  pypi:
    repository: https://repository.prod.aws.skyscnr.com/artifactory/api/pypi/pypi/simple
    username: cloudops
    password: @*DecE%lsq
    distributions:
      - sdist
      - bdist_wheel
